### ISSUE TITLE
3.0.6 install error

### ISSUE THREAD

**Issue by imapx2** [indiecrew/ProjectMRNetwork#1]
1.install error in
<import addon="repository.shani" version="2.8"/>
repository.shani-2.8 need manual install

2. Can not install or update the add-on 3.0.6  in Project MR Network.

3. version 3.0.5. It does NOT update the add-on to MR Network TV 3.0.6.﻿

 Thank you

**Comment by indiecrew** [comment]
Thank you
Already fix it in add-on 3.0.7

**Comment by imapx2** [comment]
thans too
